image: node:17.6.0-alpine3.15

stages:
- test
test:
  stage: test
  script:
    - npm install
    - npm run test

cypress:
  image: cypress/browsers:node14.17.0-chrome91-ff89
  stage: test
  script:
   - npm ci
   - npm run start &
   - npx cypress run --browser firefox