image: node:17.6.0-alpine3.15

stages:
- test
test:
  stage: test
  script:
    - npm install
    - npm run test

cypress:
  image: cypress/browsers:node12.14.1-chrome85-ff81
  stage: test
  script:
   - npm install
   - npm run start
   - npx cypress run --browser firefox