name: Continuous Integration

on:
  push:
    branches:
      - main

env:
  NODE_VERSION: "17.6.0"

jobs:
  test-unit:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Install dependencies
      run: npm install
    - name: Run tests
      run: npm run test
